# -*- coding: utf-8 -*-
"""PythonAssignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idbUuQk_W88dFhkxnWJWLy98msYCMDaM

Q1: Sort the given list of tuples based on integer value using a lambda function.

Given List:
[('Sachin Tendulkar', 34357), ('Ricky Ponting', 27483), ('Jack Kallis', 25534), ('Virat Kohli', 24936)]

Answer:
"""

data = [('Sachin Tendulkar', 34357), ('Ricky Ponting', 27483), ('Jack Kallis', 25534), ('Virat Kohli', 24936)]
sorted_data = sorted(data, key=lambda x: x[1])
print(sorted_data)

"""Q2: Find the squares of all numbers in the given list using lambda and map functions.

Given List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Answer:
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
squared_numbers = list(map(lambda x: x ** 2, numbers))
print(squared_numbers)

"""Q3: Convert the given list of integers into a tuple of strings using map and lambda functions.

Given List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Expected Output: ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')

Answer:
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
string_tuple = tuple(map(lambda x: str(x), numbers))
print(string_tuple)

"""Q4: Compute the product of a list containing numbers from 1 to 25 using the reduce function.
Answer:
"""

from functools import reduce

numbers = list(range(1, 26))
product = reduce(lambda x, y: x * y, numbers)
print(product)

"""Q5: Filter the numbers in a given list that are divisible by 2 and 3 using the filter function.

Given List: [2, 3, 6, 9, 27, 60, 90, 120, 55, 46]
Answer :
"""

numbers = [2, 3, 6, 9, 27, 60, 90, 120, 55, 46]
filtered_numbers = list(filter(lambda x: x % 2 == 0 and x % 3 == 0, numbers))
print(filtered_numbers)

"""Q6: Find palindromes in the given list of strings using lambda and filter function.

Given List: ['python', 'php', 'aba', 'radar', 'level']
Answer :
"""

words = ['python', 'php', 'aba', 'radar', 'level']
palindromes = list(filter(lambda x: x == x[::-1], words))
print(palindromes)